### ISSUE TITLE
Simplifying and Adjusting the Layout

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#24]
[Enhancement]

I've been doing a lot of test with various styles of using Kobold and I noticed something

When you have both menus opened, (or pinned when #23 is added) the layout becomes too crammed.
And the biggest problem is when you open the menu and pin it, or uses the Gen per Action, the text shifts around A LOT. 
With token streaming this problem is exacerbated. 
This much shifting can cause confusion, and headaches. And it did, for me at least...

So, to solve this I propose we take the layout and proportions of Google Docs and MS Word. 
So, instead of having a main window that compresses and expands as we use the features, we have a main page (just like Docs) and the sides remains empty. When the user wants to use the features, they can open the side menus, and if they uses it a lot, they can pin it.

In the case of the Gens per Action, it will live outside of the page, and it can pop to the other side easily.

This will stop the text from going everywhere, and will make the experience less disorientated.
And it also fix another annoyance, when you open a side menu, it will obstruct the text :D

**Comment by ebolam** [comment]
New Design to minimize text reflow:
1. Game area is always split into game text and options, even if options aren't visible
2. If menu(s) is pinned open, it reserves space, otherwise it goes over the text when opened
3. Options moves to the left side if the story menu is pinned but the settings menu is not.
4. If both menu's are unpinned, reserve left space for art (to keep main game-text centered)

**Comment by ebolam** [comment]
Done
